#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDAPPLY                                 3
#define IDR_DOWNARROW                           101
#define IDR_DOWNARROW_HOVER                     102
#define IDR_DOWNARROW_INACT                     103
#define IDR_DOWNARROW_PUSH                      104
#define IDD_CHOOSE_MULTIPLE_LANGUAGES           106
#define IDD_ABOUT                               107
#define IDC_SUGGESTIONS_NUM                     1001
#define IDR_CLOSETAB_HOVER                      1001
#define IDC_SUGG_TYPE                           1002
#define IDR_CLOSETAB_PUSH                       1002
#define IDC_LIBRARY                             1003
#define IDR_CLOSETAB                            1003
#define IDC_DEFAULT_DELIMITERS                  1004
#define IDR_CLOSETAB_INACT                      1004
#define IDC_COMBO_LANGUAGE                      1005
#define IDC_ASPELLPATH                          1006
#define IDC_DELIMETERS                          1006
#define IDC_BROWSEASPELLPATH                    1007
#define IDD_SIMPLE                              1007
#define IDD_ADVANCED                            1008
#define IDC_RESETASPELLPATH                     1009
#define IDD_SETTINGS                            1009
#define IDC_COUNT_YO_AS_YE                      1011
#define IDD_SUGGESTIONS                         1011
#define IDC_ASPELL_STATUS                       1012
#define IDC_RECHECK_DELAY                       1012
#define IDC_FILETYPES                           1013
#define IDC_FILETYPES_CHECKTHOSE                1015
#define IDC_FILETYPES_CHECKNOTTHOSE             1016
#define IDC_BUFFER_SIZE                         1017
#define IDC_IGNORE_NUMBERS                      1019
#define IDC_IGNORE_CSTART                       1020
#define IDC_IGNORE_CHAVE                        1021
#define IDC_COUNT_SINGLE_QUOTES_AS_APOSTROPHE   1022
#define IDC_SYSLINK1                            1023
#define IDC_UNDERLINE_COLOR                     1024
#define IDC_UNDERLINE_STYLE                     1025
#define IDC_SLIDER_SIZE                         1029
#define IDC_SLIDER_TRANSPARENCY                 1030
#define IDC_CHECKCOMMENTS                       1031
#define IDC_LANGLIST                            1032
#define IDC_IGNORE_                             1036
#define IDC_IGNORE_CALL                         1037
#define IDC_SYSLINK2                            1038
#define IDC_IGNORE_SE_APOSTROPHE                1039
#define IDC_LIB_LINK                            1039
#define IDC_LIB_GROUPBOX                        1040
