#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDAPPLY                                 3
#define IDR_DOWNARROW                           101
#define IDR_DOWNARROW_HOVER                     102
#define IDR_DOWNARROW_PUSH                      104
#define IDD_CHOOSE_MULTIPLE_LANGUAGES           106
#define IDD_ABOUT                               107
#define IDD_DOWNLOADDICS                        109
#define IDD_DIALOGPROGRESS                      111
#define IDD_REMOVE_DICS                         113
#define IDI_REFRESH                             128
#define IDB_AUTOCHECK                           141
#define IDD_DIALOG_SELECT_PROXY                 143
#define IDB_AUTOCHECK2                          145
#define IDC_VERSION                             1000
#define IDC_IGNORE_ONE_LETTER                   1001
#define IDC_REMOVE_LANGLIST                     1001
#define IDC_SHOWONLYKNOWN                       1001
#define IDC_STOP                                1001
#define IDC_SUGGESTIONS_NUM                     1001
#define IDC_SYSLINK3                            1001
#define IDC_REFRESH                             1002
#define IDC_REMOVE_ENDING_APOSTROPHE            1002
#define IDC_REMOVE_USER_DICS                    1002
#define IDC_SUGG_TYPE                           1002
#define IDC_LIBRARY                             1003
#define IDC_REMOVE_SYSTEM                       1003
#define IDC_DEFAULT_DELIMITERS                  1004
#define IDC_DOWNLOADDICS                        1004
#define IDC_COMBO_LANGUAGE                      1005
#define IDC_INSTALL_SYSTEM                      1005
#define IDC_ASPELLPATH                          1006
#define IDC_BROWSEASPELLPATH                    1007
#define IDC_HOSTNAME                            1007
#define IDD_SIMPLE                              1007
#define IDC_ONE_USER_DIC                        1008
#define IDC_USERNAME                            1008
#define IDD_ADVANCED                            1008
#define IDC_ADDRESS                             1009
#define IDC_PORT                                1009
#define IDD_SETTINGS                            1009
#define IDC_DECODE_NAMES                        1010
#define IDC_FILE_LIST                           1010
#define IDC_PASSWORD                            1010
#define IDC_COUNT_YO_AS_YE                      1011
#define IDC_SERVER_STATUS                       1011
#define IDC_USEPROXY                            1011
#define IDD_SUGGESTIONS                         1011
#define IDC_ASPELL_STATUS                       1012
#define IDC_RECHECK_DELAY                       1012
#define IDC_FILETYPES                           1013
#define IDC_REMOVE_DICS                         1014
#define IDC_FILETYPES_CHECKTHOSE                1015
#define IDC_SELECTPROXY                         1015
#define IDC_FILETYPES_CHECKNOTTHOSE             1016
#define IDC_PROGRESSBAR                         1016
#define IDC_BUFFER_SIZE                         1017
#define IDC_ANONYMOUS_LOGIN                     1019
#define IDC_HUNSPELL_PATH_TYPE                  1019
#define IDC_IGNORE_NUMBERS                      1019
#define IDC_IGNORE_CSTART                       1020
#define IDC_IGNORE_CHAVE                        1021
#define IDC_SYSTEMPATH                          1021
#define IDC_COUNT_SINGLE_QUOTES_AS_APOSTROPHE   1022
#define IDC_PROXY_TYPE                          1023
#define IDC_SYSLINK1                            1023
#define IDC_UNDERLINE_COLOR                     1024
#define IDC_UNDERLINE_STYLE                     1025
#define IDC_SLIDER_SIZE                         1029
#define IDC_SLIDER_TRANSPARENCY                 1030
#define IDC_LANGLIST                            1032
#define IDC_IGNORE_                             1036
#define IDC_IGNORE_CALL                         1037
#define IDC_SYSLINK2                            1038
#define IDC_IGNORE_SE_APOSTROPHE                1039
#define IDC_LIB_LINK                            1039
#define IDC_DESCBOTTOM                          1040
#define IDC_LIB_GROUPBOX                        1040
#define IDC_DESCTOP                             1041
#define IDC_HUNSPELL_PATH_GROUPBOX              1041
#define IDC_RESETSPELLERPATH                    40000
#define IDC_TOKENIZATION_STYLE_CMB              40000
#define IDS_DICT_PS_EXISTS_BODY                 40000
#define IDC_ASPELL_RUNTOGETHER_CB               40001
#define IDC_DELIMITERS                          40001
#define IDS_CANT_CREATE_DIR_PS                  40001
#define IDC_DELIMITER_EXCLUSIONS_LE             40002
#define IDC_LIB_CODE_GB                         40002
#define IDS_STATUS_HTML_PARSING_FAIL            40002
#define IDC_CAMEL_CASE_SPLITTING_CB             40003
#define IDS_STATUS_LOADING                      40003
#define IDC_CHECKFUNCVAR_CB                     40004
#define IDS_STATUS_LIST_SUCCESS                 40004
#define IDC_CHECKCOMMENTS_CB                    40005
#define IDS_STATUS_PROXY_AUTH_REQUIRED          40005
#define IDC_CHECKSTRINGS_CB                     40006
#define IDS_MULTIPLE_LANGUAGES                  40006
#define IDS_SET_MULTIPLE_LANG                   40007
#define IDS_ERROR_IN_DIR_CREATE                 40008
#define IDS_STATUS_FILE_CANNOT_BE_WRITTEN       40009
#define IDS_DOWNLOAD_LANGS                      40010
#define IDS_STATUS_DOWNLOAD_CANCELLED           40011
#define IDS_DOWNLOAD_LANG                       40012
#define IDS_STATUS_BAD_CONNECTION               40013
#define IDS_STATUS_CANT_LIST_FILES              40014
#define IDS_STATUS_HTTP_CLIENT_INIT_FAIL        40015
#define IDS_REMOVE_LANG                         40016
#define IDS_STATUS_URL_OPEN_FAIL                40017
#define IDS_STATUS_HTTP_CODE_QUERY_FAIL         40018
#define IDS_STATUS_DIRECTORY_EMPTY              40019
#define IDS_HIDDEN                              40020
#define IDS_SPECIAL_SUGGESTION_BUTTON           40021
#define IDS_DIAGONAL                            40022
#define IDS_ASPELL                              40023
#define IDS_ASPELL_LIBRARY_DLL_FILTER           40024
#define IDS_USER_DICT_CANT_SAVE_TITLE           40025
#define IDS_SPLIT_WORDS_BY_NON_ALPHA            40026
#define IDS_SPLIT_WORDS_BY_DELIMS               40027
#define IDS_DASH                                40028
#define IDS_USER_DICT_CANT_SAVE_BODY            40029
#define IDS_SQUIGGLE_LOW                        40030
#define IDS_NATIVE_WINDOWS                      40031
#define IDS_NATIVE_SPELLER                      40032
#define IDS_SQUIGGLE                            40033
#define IDS_CYRILLIC_YO_AS_YE                   40034
#define IDS_ASPELL_LOCATION                     40035
#define IDS_HUNSPELL                            40036
#define IDS_HUNSPELL_SETTINGS                   40037
#define IDS_STRAIGHT_BOX                        40038
#define IDS_FOR_ALL_USERS                       40039
#define IDS_ASPELL_STATUS_OK                    40040
#define IDS_BOX                                 40041
#define IDS_ASPELL_STATUS_FAIL                  40042
#define IDS_USE_NPP_CONTEXT_MENU                40043
#define IDS_WORD_CANT_BE_ADDED                  40044
#define IDS_STRIKE                              40045
#define IDS_FOR_CURRENT_USER                    40046
#define IDS_FTP_GATEWAY                         40047
#define IDS_DOTS                                40048
#define IDS_ROUND_BOX                           40049
#define IDS_ADDITIONAL_ACTIONS                  40050
#define IDS_FTP_WEB_PROXY                       40051
#define IDS_ASPELL_STATUS_NO_DICTS              40052
#define IDS_PICK_A_DIRECTORY                    40053
#define IDS_TT                                  40054
#define IDC_ERROR_BAD_ENCODING                  40055
#define IDS_PLAIN                               40056
#define IDS_PD_DICTIONARIES_REMOVED             40057
#define IDS_AUTO_SPELL_CHECK                    40058
#define IDS_FIND_NEXT_ERROR                     40059
#define IDS_FIND_PREV_ERROR                     40060
#define IDS_CHANGE_CURRENT_LANG                 40061
#define IDS_SETTINGS                            40062
#define IDS_COPY_ALL_MISSPELLED                 40063
#define IDS_RELOAD_HUNSPELL                     40064
#define IDS_ONLINE_MANUAL                       40065
#define IDS_ABOUT                               40066
#define IDS_DICT_EXISTS_HEADER                  40067
#define IDS_DICTS_COPIED                        40068
#define IDS_TEMPORARY_PATH_INVALID_HEADER       40069
#define IDS_TEMPORARY_PATH_INVALID_BODY         40070
#define IDS_NO_DICTS_DOWNLOADED                 40071
#define IDS_CANT_CREATE_DOWNLOAD_DIR            40072
#define IDS_CANT_WRITE_DICT_FILES               40073
#define IDS_DICTS_DOWNLOADED                    40074
#define IDS_ZERO_DICTS_DOWNLOAD                 40075
#define IDS_EXTRACTING_PS                       40076
#define IDS_DOWNLOADING_PS                      40077
#define IDS_PD_OF_PD_BYTES_DOWNLOADED_PD        40078
#define IDS_PD_BYTES_DOWNLOADED                 40079
#define IDS_STATUS_HTTP_ERROR_PD                40080
