#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDAPPLY                                 3
#define IDR_DOWNARROW                           101
#define IDR_DOWNARROW_HOVER                     102
#define IDR_DOWNARROW_PUSH                      104
#define IDD_CHOOSE_MULTIPLE_LANGUAGES           106
#define IDD_ABOUT                               107
#define IDD_DOWNLOADDICS                        109
#define IDD_DIALOGPROGRESS                      111
#define IDD_REMOVE_DICS                         113
#define IDI_REFRESH                             128
#define IDB_AUTOCHECK                           141
#define IDD_DIALOG_SELECT_PROXY                 143
#define IDB_AUTOCHECK2                          145
#define IDC_VERSION                             1000
#define IDC_IGNORE_ONE_LETTER                   1001
#define IDC_REMOVE_LANGLIST                     1001
#define IDC_SHOWONLYKNOWN                       1001
#define IDC_STOP                                1001
#define IDC_SUGGESTIONS_NUM                     1001
#define IDC_SYSLINK3                            1001
#define IDC_REFRESH                             1002
#define IDC_REMOVE_ENDING_APOSTROPHE            1002
#define IDC_REMOVE_USER_DICS                    1002
#define IDC_SUGG_TYPE                           1002
#define IDC_LIBRARY                             1003
#define IDC_REMOVE_SYSTEM                       1003
#define IDC_DEFAULT_DELIMITERS                  1004
#define IDC_DOWNLOADDICS                        1004
#define IDC_COMBO_LANGUAGE                      1005
#define IDC_INSTALL_SYSTEM                      1005
#define IDC_ASPELLPATH                          1006
#define IDC_DELIMETERS                          1006
#define IDC_BROWSEASPELLPATH                    1007
#define IDC_HOSTNAME                            1007
#define IDD_SIMPLE                              1007
#define IDC_ONE_USER_DIC                        1008
#define IDC_USERNAME                            1008
#define IDD_ADVANCED                            1008
#define IDC_ADDRESS                             1009
#define IDC_PORT                                1009
#define IDD_SETTINGS                            1009
#define IDC_DECODE_NAMES                        1010
#define IDC_FILE_LIST                           1010
#define IDC_PASSWORD                            1010
#define IDC_COUNT_YO_AS_YE                      1011
#define IDC_SERVER_STATUS                       1011
#define IDC_USEPROXY                            1011
#define IDD_SUGGESTIONS                         1011
#define IDC_ASPELL_STATUS                       1012
#define IDC_RECHECK_DELAY                       1012
#define IDC_FILETYPES                           1013
#define IDC_REMOVE_DICS                         1014
#define IDC_FILETYPES_CHECKTHOSE                1015
#define IDC_SELECTPROXY                         1015
#define IDC_FILETYPES_CHECKNOTTHOSE             1016
#define IDC_PROGRESSBAR                         1016
#define IDC_BUFFER_SIZE                         1017
#define IDC_ANONYMOUS_LOGIN                     1019
#define IDC_HUNSPELL_PATH_TYPE                  1019
#define IDC_IGNORE_NUMBERS                      1019
#define IDC_IGNORE_CSTART                       1020
#define IDC_IGNORE_CHAVE                        1021
#define IDC_SYSTEMPATH                          1021
#define IDC_COUNT_SINGLE_QUOTES_AS_APOSTROPHE   1022
#define IDC_PROXY_TYPE                          1023
#define IDC_SYSLINK1                            1023
#define IDC_UNDERLINE_COLOR                     1024
#define IDC_UNDERLINE_STYLE                     1025
#define IDC_SLIDER_SIZE                         1029
#define IDC_SLIDER_TRANSPARENCY                 1030
#define IDC_CHECKCOMMENTS                       1031
#define IDC_LANGLIST                            1032
#define IDC_IGNORE_                             1036
#define IDC_IGNORE_CALL                         1037
#define IDC_SYSLINK2                            1038
#define IDC_IGNORE_SE_APOSTROPHE                1039
#define IDC_LIB_LINK                            1039
#define IDC_DESCBOTTOM                          1040
#define IDC_LIB_GROUPBOX                        1040
#define IDC_DESCTOP                             1041
#define IDC_HUNSPELL_PATH_GROUPBOX              1041
#define IDC_RESETSPELLERPATH                    40000
